apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: liocko/backend-flask  
        ports:
          - containerPort: 5001
        env:
          - name: POSTGRES_DB
            value: "insurancedb"
          - name: POSTGRES_USER
            value: "liocko"
          - name: POSTGRES_PASSWORD
            value: "password"
          - name: POSTGRES_HOST
            value: "postgres-service"
        envFrom:
          - configMapRef:
              name: backend-config

---

apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: ClusterIP
