version: '3.9'
services:
  postgres:
    image: postgres:14.8-alpine3.18
    environment:
      POSTGRES_DB: "insurancedb"
      POSTGRES_USER: "liocko"
      POSTGRES_PASSWORD: "password"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      - postgres
    environment:
      - POSTGRES_DB=insurancedb
      - POSTGRES_USER=liocko
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=postgres
    env_file:
      - .env

volumes:
  pgdata:
